version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.1
    - 11.2.7
    - 11.2.8
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.1
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1101.1
    - 0.1101.2
    - 0.1101.4
    - 0.1102.0
    - 0.1102.1
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: "@uirouter/angular"
    versions:
    - 8.0.1
  - dependency-name: "@ngtools/webpack"
    versions:
    - 11.2.2
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
    - 4.5.2
  - dependency-name: typescript
    versions:
    - 4.0.7
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: node-sass
    versions:
    - 5.0.0
